In [0]:
print("Hello World")

Hello World

In [0]:
%sql
SELECT "Hello World"

"""Hello World"""
Hello World

In [0]:
# https://raw.githubusercontent.com/guilhermeonrails/i-eng-dados-26/refs/heads/main/dados.csv

import pandas as pd # importando a biblioteca pandas como pd para facilitar a escrita do código

In [0]:
df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/i-eng-dados-26/refs/heads/main/dados.csv") #df = dataframe

In [0]:
df.head(10)

   id_usuario  home  ...  codigo_compra  valor_total
0  USR1000001     1  ...            NaN          NaN
1  USR1000002     1  ...            NaN          NaN
2  USR1000003     1  ...            NaN          NaN
3  USR1000004     1  ...            NaN          NaN
4  USR1000005     1  ...            NaN          NaN
5  USR1000006     1  ...            NaN          NaN
6  USR1000007     1  ...            NaN          NaN
7  USR1000008     1  ...            NaN          NaN
8  USR1000009     1  ...            NaN          NaN
9  USR1000010     1  ...            NaN          NaN

[10 rows x 10 columns]

In [0]:
#sempre que quero acessar o df (dataframe) usar :

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id_usuario           495000 non-null  object
 1   home                 500000 non-null  int64
 2   pesquisou_produto    500000 non-null  int64
 3   visualizou_detalhes  500000 non-null  int64
 4   acessou_faq          500000 non-null  int64
 5   acessou_ofertas      500000 non-null  int64
 6   adicionou_carrinho   500000 non-null  int64
 7   finalizou_compra     500000 non-null  int64
 8   codigo_compra        39726 non-null   object
 9   valor_total          39726 non-null   float64
dtypes: float64(1), int64(7), object(2)
memory usage: 38.1+ MB

In [0]:
df.isnull().sum() #verificando se tem algum dado nulo

id_usuario               5000
home                        0
pesquisou_produto           0
visualizou_detalhes         0
acessou_faq                 0
acessou_ofertas             0
adicionou_carrinho          0
finalizou_compra            0
codigo_compra          460274
valor_total            460274
dtype: int64

In [0]:
df ['id_usuario'] = df ['id_usuario'].fillna('USER_DESCONHECIDO')

In [0]:
df.head()

   id_usuario  home  ...  codigo_compra  valor_total
0  USR1000001     1  ...            NaN          NaN
1  USR1000002     1  ...            NaN          NaN
2  USR1000003     1  ...            NaN          NaN
3  USR1000004     1  ...            NaN          NaN
4  USR1000005     1  ...            NaN          NaN

[5 rows x 10 columns]

In [0]:
df[df['id_usuario'] == 'USER_DESCONHECIDO']

               id_usuario  home  ...  codigo_compra  valor_total
212     USER_DESCONHECIDO     1  ...            NaN          NaN
299     USER_DESCONHECIDO     1  ...            NaN          NaN
354     USER_DESCONHECIDO     1  ...            NaN          NaN
569     USER_DESCONHECIDO     1  ...            NaN          NaN
603     USER_DESCONHECIDO     1  ...            NaN          NaN
...                   ...   ...  ...            ...          ...
499648  USER_DESCONHECIDO     1  ...            NaN          NaN
499858  USER_DESCONHECIDO     1  ...      CMP160834      4541.79
499872  USER_DESCONHECIDO     1  ...            NaN          NaN
499908  USER_DESCONHECIDO     1  ...      CMP200979      3048.02
499957  USER_DESCONHECIDO     1  ...            NaN          NaN

[5000 rows x 10 columns]

In [0]:
df.head()

   id_usuario  home  ...  codigo_compra  valor_total
0  USR1000001     1  ...            NaN          NaN
1  USR1000002     1  ...            NaN          NaN
2  USR1000003     1  ...            NaN          NaN
3  USR1000004     1  ...            NaN          NaN
4  USR1000005     1  ...            NaN          NaN

[5 rows x 10 columns]

In [0]:
df.isnull().sum()

id_usuario                  0
home                        0
pesquisou_produto           0
visualizou_detalhes         0
acessou_faq                 0
acessou_ofertas             0
adicionou_carrinho          0
finalizou_compra            0
codigo_compra          460274
valor_total            460274
dtype: int64

In [0]:
spark.createDataFrame(df).createOrReplaceTempView("dados")

In [0]:
dados_spark = spark.createDataFrame(df)

In [0]:
%sql
SELECT * 
FROM dados
LIMIT 5

id_usuario,home,pesquisou_produto,visualizou_detalhes,acessou_faq,acessou_ofertas,adicionou_carrinho,finalizou_compra,codigo_compra,valor_total
USR1000001,1,1,1,0,1,1,0,null,null
USR1000002,1,1,1,0,1,0,0,null,null
USR1000003,1,1,0,1,1,0,0,null,null
USR1000004,1,1,1,0,0,0,0,null,null
USR1000005,1,0,0,1,0,0,0,null,null